sudo: required
services:
  - docker

before_install:
  - docker build -t tqvdang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tqvdang/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-967098599925"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY